import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#001e2d',
        'outline': '#867461',
        'status-warning': '#d97706',
        'on-surface-variant': '#534434',
        'border-subtle': '#e2e8f0',
        'on-secondary-fixed': '#131b2e',
        'on-secondary-container': '#5c647a',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'primary-fixed': '#ffddb8',
        'text-main': '#0f172a',
        'tertiary': '#00658b',
        'primary-fixed-dim': '#ffb95f',
        'secondary': '#565e74',
        'surface-container-high': '#e6e8ea',
        'background': '#f7f9fb',
        'surface-container-highest': '#e0e3e5',
        'inverse-surface': '#2d3133',
        'surface-container': '#f1f5f9',
        'on-tertiary': '#ffffff',
        'status-critical': '#dc2626',
        'on-secondary': '#ffffff',
        'on-primary-container': '#613b00',
        'status-nominal': '#16a34a',
        'surface-variant': '#e0e3e5',
        'on-background': '#191c1e',
        'on-secondary-fixed-variant': '#3f465c',
        'surface-container-low': '#f2f4f6',
        'on-primary-fixed-variant': '#653e00',
        'tertiary-fixed-dim': '#7fd0ff',
        'on-error': '#ffffff',
        'tertiary-fixed': '#c5e7ff',
        'surface-tint': '#855300',
        'surface': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#1abdff',
        'surface-bright': '#f7f9fb',
        'on-tertiary-fixed-variant': '#004c6a',
        'primary-container': '#f59e0b',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#eff1f3',
        'secondary-fixed': '#dae2fd',
        'secondary-fixed-dim': '#bec6e0',
        'on-primary': '#ffffff',
        'outline-variant': '#d8c3ad',
        'on-primary-fixed': '#2a1700',
        'on-surface': '#191c1e',
        'primary': '#855300',
        'on-tertiary-container': '#004966',
        'secondary-container': '#dae2fd',
        'surface-dim': '#d8dadc',
        'inverse-primary': '#ffb95f',

        // Legacy compatibility aliases
        danger: {
          50: '#fef2f2',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
        },
        warning: {
          50: '#fffbeb',
          500: '#f59e0b',
          600: '#d97706',
        },
        safe: {
          50: '#f0fdf4',
          500: '#22c55e',
          600: '#16a34a',
        },
      },
      borderRadius: {
        none: '0px',
        sm: '6px',
        DEFAULT: '6px',
        md: '6px',
        lg: '6px',
        xl: '6px',
        '2xl': '6px',
        '3xl': '6px',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '1rem',
        'sidebar-width': '256px',
        'sidebar-icon-width': '64px',
        'rail-width': '64px',
        'unit': '4px',
        'gutter': '1rem',
        'margin-desktop': '1.5rem',
        'topbar-height': '56px',
      },
      fontFamily: {
        sans: ['Space Grotesk', 'sans-serif'],
        'headline-md-mobile': ['Space Grotesk', 'sans-serif'],
        'stat-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'label-caps': ['Space Grotesk', 'sans-serif'],
        'body-bold': ['Space Grotesk', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'telemetry-md': ['Space Grotesk', 'sans-serif'],
        'body-base': ['Space Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-md-mobile': ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'stat-lg': ['28px', { lineHeight: '32px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
        'body-bold': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '800' }],
        'telemetry-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-base': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};

export default config;

